[workspace]
resolver = "2"
members = [
    "databases-d6",
    "databases-d7",
    "databases-serde",
    "dll-injector-dinput8",
    "dsarcfl",
    "fafullfs",
    "modloader-d6",
    "modloader-d7",
    "nlsd",
    "ykcmp",
]
