[package]
name = "makaikit-fafullfs"
version = "0.1.0-alpha.0"
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
thiserror = "1"

[dev-dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
