name: windows
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: x64
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - name: Dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            target/release/dinput8.dll
            target/release/makaikit_modloader_d6.dll
